apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlegrocery-deployment
  labels:
    app: googlegrocery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: googlegrocery
  template:
    metadata:
      labels:
        app: googlegrocery
    spec:
      containers:
      - name: googlegrocery
          image: 992382394001.dkr.ecr.us-east-1.amazonaws.com/shopping-site-googlegrocery:3676f13683b84fd6790140476a1c3c51ee56ac1d
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: googlegrocery-service
  labels:
    app: googlegrocery
spec:
  type: ClusterIP
  selector:
    app: googlegrocery
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
